# CircleCI configuration for Energy Manager IoT
version: 2.1

orbs:
  node: circleci/node@5.1.0
  codecov: codecov/codecov@3.2.4

jobs:
  lint-and-format:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run linting
          command: npm run lint
      - run:
          name: Check formatting
          command: npm run format -- --check

  test:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests with coverage
          command: npm run test:coverage
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: junit.xml
      - codecov/upload

  build:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build library
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - package.json
            - README.md

  docs:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install typedoc
          command: npm install -g typedoc
      - run:
          name: Generate documentation
          command: typedoc --out docs src/index.ts
      - store_artifacts:
          path: docs
      - persist_to_workspace:
          root: .
          paths:
            - docs

  publish:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - node/install-packages
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to NPM
          command: npm publish --access public

workflows:
  version: 2
  build-test-publish:
    jobs:
      - lint-and-format
      - test:
          requires:
            - lint-and-format
      - build:
          requires:
            - test
      - docs:
          requires:
            - test
      - publish:
          requires:
            - build
            - docs
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
