version: 2.1

jobs:
  auto-create-config:
    docker:
      - image: circleci/config-setup:latest
    steps:
      - checkout
      - run:
          name: Generate Config
          command: config-setup generate-and-add-config << pipeline.id >>
  playwright-e2e-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.43.1-jammy
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps
      - run:
          name: Run Playwright E2E Tests
          command: npx playwright test
      - store_artifacts:
          path: playwright-report
          destination: playwright-report

workflows:
  generate-config:
    jobs:
      - auto-create-config
      - playwright-e2e-test:
          requires:
            - auto-create-config
